title: alexcoder04's personal website
email: alexcoder04@protonmail.com
description: >
  My personal website built using GitHub pages and Jekyll
baseurl: ""
url: ""

theme: minima
plugins:
  - jekyll-feed
